void test_auton();
void optical_test();
void skills_matchload(int num);
void last_ball();
void pid_turn_test();
void bowl_matchload(int num);
void potential_reset(int x, int y, int target_angle);
void endgame();
void isolation();
void interaction();
void testInteraction();